<?php
if ($_GET['https'] > 0) {
    echo json_encode( array(
"https://g.eeload.com",
"https://g.weme.so",
"https://g.yh.gs",
"https://gg.kfd.me",
"https://gg.searcher.top",
"https://gg.wen.lu",
"https://google-hk.wewell.net",
"https://google.xface.me",
"https://gs.awei.me",
"https://gtlds.me",
"https://guge.in",
"https://hei.so",
"https://www.guge.click",
"https://www.guge.date",
"https://www.guge119.com",
"https://www.sslpxy.com",
) ); 
} else {
    echo json_encode( array(
"http://g.yon.hk",
"http://gg.cellmean.com",
"http://gg.cytbj.com",
"http://go.hibenben.com",
"http://google.kainidi.cn",
"http://google.sidney-aldebaran.me",
"http://hisbig.com",
"http://www.ggooo.net",
"http://www.gog.pw",
"http://www.google52.com",
"http://www.googlestable.cn",
"http://www.gufen138.com",
"http://www.guge.link",
"http://www.ppx.pw",
"http://www.wanzi138.com",
"https://g.eeload.com",
"https://g.weme.so",
"https://g.yh.gs",
"https://gg.kfd.me",
"https://gg.searcher.top",
"https://gg.wen.lu",
"https://google-hk.wewell.net",
"https://google.xface.me",
"https://gs.awei.me",
"https://gtlds.me",
"https://guge.in",
"https://hei.so",
"https://www.guge.click",
"https://www.guge.date",
"https://www.guge119.com",
"https://www.sslpxy.com",
) );
}
